name: Lint Python

steps:
  - name: Free up disk space
    run: |
      sudo rm -rf /usr/share/dotnet
      sudo rm -rf /opt/ghc
      sudo rm -rf "/usr/local/share/boost"
      sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      echo "Disk space freed."

  - name: Checkout
    uses: actions/checkout@v4
    # ... rest of your steps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "check --fix" # Adding --fix here will auto-sort those imports for you!

